const allData = [
    {
        id: 1,
        thumbnail: require('../../assets/Image/video1.jpg'),
        url: 'https://drive.google.com/uc?id=1MK6BPFJmV6iC3hE5mWAP-2x8DIqJiHF1&export=download',
        //   videoTime: videoTime[0]?.time,
        videoTime: '1.22',
        channelImage: require('../../assets/Image/ronak.jpg'),
        coverImage: require('../../assets/Image/bgimage.jpg'),
        videoTitle: 'title of video Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora quibusdam, voluptates aliquam blanditiis illo voluptas',
        channelName: 'buoyancy',
        videoView: '28k',
        videoLaunch: '1 month ago',
        categoryType: 'movie',
        subscribers: '34.2M',
        videoType:'video'

    },
    {
        id: 2,
        thumbnail: require('../../assets/Image/video2.jpg'),
        url: 'https://drive.google.com/uc?id=11LcWF7f9iFTDdops5tpM4U0EfMa-NtDO&export=download',
        videoTime: '1.16',
        channelImage: require('../../assets/Image/krupal.png'),
        coverImage: require('../../assets/Image/bgimage1.jpg'),
        videoTitle: 'illo Tempora consectetur adipisicing elit. ipsum dolor sit amet Tempora quibusdam, voluptates aliquam blanditiis illo voluptas',
        channelName: 'krupal',
        videoView: '12k',
        videoLaunch: '3 month ago',
        categoryType: 'music',
        subscribers: '14M',
        videoType:'video'

    },
    {
        id: 3,
        thumbnail: require('../../assets/Image/video3.jpg'),
        url: ' https://drive.google.com/uc?id=1ZoZhN53xYEPNdM4oNglJdnwD3TikXDNI&export=download',
        videoTime: '1.08',
        channelImage: require('../../assets/Image/ronak.jpg'),
        coverImage: require('../../assets/Image/bgimage.jpg'),
        videoTitle: 'dolor Tempora sit amet consectetur adipisicing elit. Tempora quibusdam, voluptates aliquam blanditiis illo voluptas',
        channelName: 'buoyancy',
        videoView: '13k',
        videoLaunch: '6 day ago',
        categoryType: 'gaming',
        subscribers: '34.2M',
        videoType:'video'

    },
    {
        id: 4,
        thumbnail: require('../../assets/Image/video4.jpg'),
        url: 'https://drive.google.com/uc?id=1bMeRCw-oAr4hKOybUyrXrhINEW0dno0X&export=download',
        videoTime: '1.35',
        channelImage: require('../../assets/Image/noman.jpg'),
        coverImage: require('../../assets/Image/whatsappweb.jpg'),
        videoTitle: 'adipisicing elit. Tempora quibusdam, voluptates aliquam blanditiis illo voluptas',
        channelName: 'noman',
        videoView: '8k',
        videoLaunch: '2 month ago',
        categoryType: 'movie',
        subscribers: '8.5M',
        videoType:'video'

    },
    {
        id: 5,
        thumbnail: require('../../assets/Image/video5.jpg'),
        url: 'https://drive.google.com/uc?id=143LgiKUSav2GnhfAvk3V6RX_JC3-6bce&export=download',
        videoTime: '1.15',
        channelImage: require('../../assets/Image/ronak.jpg'),
        coverImage: require('../../assets/Image/bgimage.jpg'),
        videoTitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora quibusdam, voluptates aliquam blanditiis illo voluptas',
        channelName: 'buoyancy',
        videoView: '20k',
        videoLaunch: '1.5 month ago',
        categoryType: 'music',
        subscribers: '34.2M',
        videoType:'video'

    },
    {
        id: 6,
        thumbnail: require('../../assets/Image/video6.jpg'),
        url: 'https://drive.google.com/uc?id=1_6XOtS4vT5RUhcn12iHPbiF05Yc82P-W&export=download',
        videoTime: '2.01',
        channelImage: require('../../assets/Image/krupal.png'),
        coverImage: require('../../assets/Image/bgimage1.jpg'),
        videoTitle: 'consectetur ipsum dolor sit amet consectetur adipisicing elit. Tempora quibusdam, voluptates aliquam blanditiis illo voluptas',
        channelName: 'krupal',
        videoView: '18k',
        videoLaunch: '5 month ago',
        categoryType: 'movie',
        subscribers: '14M',
        videoType:'video'

    },
    {
        id: 7,
        thumbnail: require('../../assets/Image/video7.jpg'),
        url: 'https://drive.google.com/uc?id=1ks3vMQwKz5P2TSs2rOKRUrkmWQXIcxGN&export=download',
        videoTime: '2.00',
        channelImage: require('../../assets/Image/noman.jpg'),
        coverImage: require('../../assets/Image/whatsappweb.jpg'),
        videoTitle: 'blanditiis adipisicing elit. Tempora quibusdam, voluptates aliquam blanditiis illo voluptas',
        channelName: 'noman',
        videoView: '2.8k',
        videoLaunch: '4 month ago',
        categoryType: 'gaming',
        subscribers: '8.5M',
        videoType:'video'

    },
    {
        id: 8,
        thumbnail: require('../../assets/Image/video8.png'),
        url: 'https://drive.google.com/uc?id=1qsOy_go71JrtfWiHnjX45hvkylkmvo1X&export=download',
        videoTime: '0.13',
        channelImage: require('../../assets/Image/krupal.png'),
        coverImage: require('../../assets/Image/bgimage1.jpg'),
        videoTitle: 'ipsum dolor sit amet title of video Lorem, aamet consectetur adipisicing elit. Tempora quibusdam, voluptates aliquam blanditiis illo voluptas',
        channelName: 'krupal',
        videoView: '2.8k',
        videoLaunch: '4 month ago',
        categoryType: 'gaming',
        subscribers: '14M',
        videoType:'shorts'
    },
    {
        id: 9,
        thumbnail: require('../../assets/Image/video9.png'),
        url: 'https://drive.google.com/uc?id=1oNL5wQuNQmFaz9zZ7WvatKFiPEI5h6ab&export=download',
        videoTime: '0.21',
        channelImage: require('../../assets/Image/noman.jpg'),
        coverImage: require('../../assets/Image/whatsappweb.jpg'),
        videoTitle: 'Tempora quibusdam adipisicing elit.  quibusdam, voluptates aliquam blanditiis illo voluptas',
        channelName: 'noman',
        videoView: '2.8k',
        videoLaunch: '4 month ago',
        categoryType: 'gaming',
        subscribers: '8.5M',
        videoType:'shorts'

    },
    {
        id: 10,
        thumbnail: require('../../assets/Image/video10.png'),
        url: 'https://drive.google.com/uc?id=1Ll9KowGW1SRJgTQP3adQgohFcXnttxzX&export=download',
        videoTime: '0.04',
        channelImage: require('../../assets/Image/ronak.jpg'),
        coverImage: require('../../assets/Image/bgimage.jpg'),
        videoTitle: 'Tempora quibusdam adipisicing elit.  quibusdam, voluptates aliquam blanditiis illo voluptas',
        channelName: 'buoyancy',
        videoView: '28k',
        videoLaunch: '4 month ago',
        categoryType: 'gaming',
        subscribers: '8.5M',
        videoType:'shorts'
    },
]
export default allData;